

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

POST http://localhost:3333/users/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}


###

GET http://localhost:3333/profile